(() => {
    const IDENTIFIER = /^[A-Za-z_][A-Za-z0-9_]*$/;
    const COLUMN_TYPES = new Set(["text", "integer", "real", "boolean", "json"]);
    const RESERVED_COLUMNS = new Set(["id", "createdAt", "updatedAt", "created_at", "updated_at"]);

    function validateSchema(schema) {
        const errors = [];
        if (!schema || typeof schema !== "object" || Array.isArray(schema)) {
            return ["Schema must be a JSON object."];
        }
        if (!Number.isInteger(schema.version) || schema.version < 1) {
            errors.push("version must be a positive integer");
        }
        if (!Array.isArray(schema.tables) || !schema.tables.length) {
            errors.push("tables must contain at least one table");
            return errors;
        }

        const tableNames = new Set();
        schema.tables.forEach((table, tableIndex) => {
            const label = `tables[${tableIndex}]`;
            if (!table || typeof table !== "object" || !IDENTIFIER.test(table.name || "")) {
                errors.push(`${label}.name must start with a letter or underscore and contain only letters, digits, and underscores`);
                return;
            }
            if (tableNames.has(table.name)) errors.push(`table '${table.name}' is defined more than once`);
            tableNames.add(table.name);
            if (!Array.isArray(table.columns) || !table.columns.length) {
                errors.push(`table '${table.name}' must define at least one column`);
                return;
            }

            const columnNames = new Set();
            table.columns.forEach((column, columnIndex) => {
                const columnLabel = `${label}.columns[${columnIndex}]`;
                if (!column || typeof column !== "object" || !IDENTIFIER.test(column.name || "")) {
                    errors.push(`${columnLabel}.name is not a valid RustFrame identifier`);
                    return;
                }
                if (RESERVED_COLUMNS.has(column.name)) errors.push(`column '${column.name}' is reserved by RustFrame`);
                if (columnNames.has(column.name)) errors.push(`table '${table.name}' defines column '${column.name}' more than once`);
                columnNames.add(column.name);
                if (!COLUMN_TYPES.has(column.type)) errors.push(`${columnLabel}.type must be text, integer, real, boolean, or json`);
                if ("required" in column && typeof column.required !== "boolean") errors.push(`${columnLabel}.required must be a boolean`);
            });
        });
        return errors;
    }

    function typeName(table) {
        let value = String(table)
            .split(/[^A-Za-z0-9]+/)
            .filter(Boolean)
            .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
            .join("");
        if (value.endsWith("s") && value.length > 1) value = value.slice(0, -1);
        return value || "Table";
    }

    function safeProperty(value) {
        return /^[A-Za-z0-9_][A-Za-z0-9_$]*$/.test(value) ? value : JSON.stringify(value);
    }

    function tsType(kind) {
        if (kind === "integer" || kind === "real") return "number";
        if (kind === "boolean") return "boolean";
        if (kind === "json") return "unknown";
        return "string";
    }

    function renderTypescript(schema) {
        const errors = validateSchema(schema);
        if (errors.length) throw new Error(errors.join("\n"));
        let output = `// Generated by rustframe codegen from database schema v${schema.version}. Do not edit.\n\nimport type { RustFrameClient } from "rustframe-api";\n\n`;
        schema.tables.forEach((table) => {
            const base = typeName(table.name);
            output += `export interface ${base}Record {\n  id: number;\n  createdAt: string;\n  updatedAt: string;\n`;
            table.columns.forEach((column) => {
                output += `  ${safeProperty(column.name)}${column.required ? "" : "?"}: ${tsType(column.type)};\n`;
            });
            output += `}\n\nexport interface ${base}Insert {\n`;
            table.columns.forEach((column) => {
                const optional = !column.required || Object.hasOwn(column, "default");
                output += `  ${safeProperty(column.name)}${optional ? "?" : ""}: ${tsType(column.type)};\n`;
            });
            output += `}\n\nexport type ${base}Update = Partial<${base}Insert>;\n\n`;
        });
        output += "export interface RustFrameTableMap {\n";
        schema.tables.forEach((table) => {
            const base = typeName(table.name);
            output += `  ${safeProperty(table.name)}: { record: ${base}Record; insert: ${base}Insert; update: ${base}Update };\n`;
        });
        output += "}\n\nexport type AppRustFrameClient = RustFrameClient<RustFrameTableMap>;\n";
        return output;
    }

    function starterFiles(schema) {
        const generated = renderTypescript(schema);
        const manifest = {
            $schema: "https://othmaneblial.github.io/rustframe/schemas/v1/rustframe.schema.json",
            schemaVersion: 1,
            app: { id: "workbench-starter", title: "Workbench Starter", windows: [{ id: "main", title: "Workbench Starter", route: "/", width: 1280, height: 820 }] },
            frontend: { devCommand: "npm run dev -- --host 127.0.0.1", buildCommand: "npm run build", devUrl: "http://127.0.0.1:5173", distDir: "dist", generatedTypes: "src/rustframe.generated.ts" },
            security: { model: "local-first", csp: "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self' http://127.0.0.1:* ws://127.0.0.1:*; object-src 'none'; base-uri 'none'; frame-ancestors 'none'", permissions: [{ window: "main", allow: ["db:read", "db:write", "db:backup", "db:restore"] }] },
            database: { schema: "data/schema.json", seeds: "data/seeds", migrations: "data/migrations" },
            filesystem: { roots: [], persistGrants: true },
            shell: { commands: [] },
            packaging: { version: "0.1.0", identifier: "dev.rustframe.workbench-starter", description: "Local-first RustFrame workbench starter", icon: "assets/icon.svg", linux: { categories: ["Utility"], keywords: ["local-first", "rustframe"] }, windows: {}, macos: {} },
        };
        return {
            "workbench-starter/package.json": JSON.stringify({ name: "workbench-starter", private: true, version: "0.1.0", type: "module", scripts: { dev: "vite", build: "vite build", typecheck: "tsc --noEmit" }, dependencies: { "rustframe-api": "=0.1.0-rc.2", typescript: "^5.9.0", vite: "^7.0.0" } }, null, 2) + "\n",
            "workbench-starter/rustframe.json": JSON.stringify(manifest, null, 2) + "\n",
            "workbench-starter/data/schema.json": JSON.stringify(schema, null, 2) + "\n",
            "workbench-starter/src/rustframe.generated.ts": generated,
            "workbench-starter/src/main.ts": `import { getRustFrame } from "rustframe-api";\nimport type { AppRustFrameClient } from "./rustframe.generated";\nimport "./style.css";\n\nconst rustframe = getRustFrame() as AppRustFrameClient;\ndocument.querySelector<HTMLDivElement>("#app")!.innerHTML = \`<main><p>RustFrame / local-first</p><h1>Your workbench starts here.</h1><button id="inspect">Inspect local database</button><pre id="output"></pre></main>\`;\ndocument.querySelector("#inspect")?.addEventListener("click", async () => {\n  document.querySelector("#output")!.textContent = JSON.stringify(await rustframe.db.info(), null, 2);\n});\n`,
            "workbench-starter/src/style.css": `:root{font-family:system-ui;color:#171915;background:#f2efe5}body{margin:0}main{width:min(720px,calc(100vw - 48px));margin:10vh auto;padding:40px;border:2px solid;box-shadow:8px 8px 0}h1{font-size:clamp(42px,8vw,82px);line-height:.9}button{padding:12px 16px;border:2px solid;background:#c7f65b;font-weight:700}pre{overflow:auto}\n`,
            "workbench-starter/index.html": `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Workbench Starter</title></head><body><div id="app"></div><script type="module" src="/src/main.ts"></script></body></html>\n`,
            "workbench-starter/assets/icon.svg": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><rect width="128" height="128" rx="18" fill="#11130f"/><path fill="#ff4d00" d="M64 0h64v128H64z"/><text x="14" y="82" fill="#f2efe5" font-family="monospace" font-size="48" font-weight="700">RF</text></svg>\n`,
            "workbench-starter/README.md": `# Workbench Starter\n\nGenerated from the validated schema in the RustFrame website.\n\n> Registry status: rustframe-api@0.1.0-rc.2 must be publicly available before npm install can complete.\n\n\`\`\`bash\nnpm install\nrustframe doctor\nrustframe dev\n\`\`\`\n`,
        };
    }

    const crcTable = Array.from({ length: 256 }, (_, index) => {
        let value = index;
        for (let bit = 0; bit < 8; bit += 1) value = value & 1 ? 0xedb88320 ^ (value >>> 1) : value >>> 1;
        return value >>> 0;
    });
    const crc32 = (bytes) => {
        let value = 0xffffffff;
        bytes.forEach((byte) => { value = crcTable[(value ^ byte) & 0xff] ^ (value >>> 8); });
        return (value ^ 0xffffffff) >>> 0;
    };
    const le16 = (value) => Uint8Array.of(value & 255, (value >>> 8) & 255);
    const le32 = (value) => Uint8Array.of(value & 255, (value >>> 8) & 255, (value >>> 16) & 255, (value >>> 24) & 255);
    const joinBytes = (parts) => {
        const output = new Uint8Array(parts.reduce((total, part) => total + part.length, 0));
        let offset = 0;
        parts.forEach((part) => { output.set(part, offset); offset += part.length; });
        return output;
    };

    function buildStarterZip(schema) {
        const encoder = new TextEncoder();
        const localParts = [];
        const centralParts = [];
        let offset = 0;
        Object.entries(starterFiles(schema)).forEach(([name, contents]) => {
            const nameBytes = encoder.encode(name);
            const data = encoder.encode(contents);
            const checksum = crc32(data);
            const local = joinBytes([le32(0x04034b50), le16(20), le16(0), le16(0), le16(0), le16(0), le32(checksum), le32(data.length), le32(data.length), le16(nameBytes.length), le16(0), nameBytes, data]);
            localParts.push(local);
            centralParts.push(joinBytes([le32(0x02014b50), le16(20), le16(20), le16(0), le16(0), le16(0), le16(0), le32(checksum), le32(data.length), le32(data.length), le16(nameBytes.length), le16(0), le16(0), le16(0), le16(0), le32(0), le32(offset), nameBytes]));
            offset += local.length;
        });
        const central = joinBytes(centralParts);
        const end = joinBytes([le32(0x06054b50), le16(0), le16(0), le16(centralParts.length), le16(centralParts.length), le32(central.length), le32(offset), le16(0)]);
        return joinBytes([...localParts, central, end]);
    }

    function downloadStarter(schema) {
        const bytes = buildStarterZip(schema);
        const url = URL.createObjectURL(new Blob([bytes], { type: "application/zip" }));
        const anchor = document.createElement("a");
        anchor.href = url;
        anchor.download = "rustframe-workbench-starter.zip";
        anchor.click();
        window.setTimeout(() => URL.revokeObjectURL(url), 1000);
    }

    globalThis.RustFrameSiteTools = { validateSchema, renderTypescript, starterFiles, buildStarterZip, downloadStarter };
})();
