// Generated by rustframe codegen from database schema v1. Do not edit.

import type { RustFrameClient } from "rustframe-api";

export interface ProjectRecord {
  id: number;
  createdAt: string;
  updatedAt: string;
  title: string;
  status: string;
  notes?: string;
  pinned?: boolean;
}

export interface ProjectInsert {
  title: string;
  status?: string;
  notes?: string;
  pinned?: boolean;
}

export type ProjectUpdate = Partial<ProjectInsert>;

export interface RustFrameTableMap {
  projects: { record: ProjectRecord; insert: ProjectInsert; update: ProjectUpdate };
}

export type AppRustFrameClient = RustFrameClient<RustFrameTableMap>;
